---
spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: jdbc:postgresql://localhost:5432/tfjdbc
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

jwt:
  secret: LPUlAj5LFZEXeedXz1ZnlSCQOLtDemSHHHJFtQCWo0sFjNXUOh92zzqJuHXjREqrcGFFPU
  issuer: be.technofuturtic.formation.java
  expiration: 60

server:
  port: 8080
---
spring:
  config:
    activate:
      on-profile: prod